name: Auto-assign

on:
  issues:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

concurrency:
  group: auto-assign
  cancel-in-progress: false

permissions: {}

jobs:
  auto-assign:
    permissions:
      issues: write
      pull-requests: write
    uses: roquerodrigo/workflows/.github/workflows/auto-assign.yml@main
