name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    uses: roquerodrigo/.github/.github/workflows/npm-lint.yml@v3

  build:
    needs: lint
    uses: roquerodrigo/.github/.github/workflows/npm-build.yml@v3

  tests:
    needs: lint
    uses: roquerodrigo/.github/.github/workflows/npm-tests.yml@v3
